# Generated by Django 4.1.7 on 2023-02-25 16:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_sponsor_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
